package asynchomework.eventapi;

public enum EventName {
  USER_STREAM,
  USER_CREATED,
  TASK_ASSIGNED,
  TASK_STREAM,
  TASK_CREATED,
  TASK_RESOLVED,
  ACCOUNT_STREAM,
  ACCOUNT_BALANCE_CHANGED,
}
